# Task 1:

### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [4]:
def div(x, y):
    try:
        result = x / y
        print("Answer is :", result)
    except ZeroDivisionError:
        print("Division by zero is not allowed")
div(5,4)
div(5,0)

Answer is : 1.25
Division by zero is not allowed


### 2.Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
### Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
### subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]

In [5]:
sub=["Americans ","Indians"]
verb=["play","watch"]
obj=["Baseball","Cricket"]

for x in sub:
    for y in verb:
        for z in obj:
            print(x+" "+y+" "+z+".")

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# TASK 2:

### 1. Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
### HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [7]:
import numpy as ab
i = ab.array([2,3,4,1])
j = 6
ab.vander(i,j)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [8]:
ab.vander(i,j,increasing=False)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [9]:
ab.vander(i,j,increasing=True)


array([[   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    1,    1,    1,    1,    1]])

In [10]:
ab.vander(i,increasing=False)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])